# aqui haremos las peticiones
server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: usuarios
            uri: lb://msvc-usuarios  # Utiliza el nombre del servicio registrado en Eureka
            predicates:
              - Path=/api/usuarios/**
          - id: respuesta
            uri: lb://msvc-respuesta
            predicates:
              - Path=/api/respuestas/**
          - id: hilos
            uri: lb://msvc-hilos
            predicates:
              - Path=/api/hilos/**
          - id: estados
            uri: lb://msvc-estados
            predicates:
              - Path=/api/estados/**

# Configuración de Eureka
eureka:
  instance:
    hostname: 54.90.34.44
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/