server:
  port: 9093

spring:
  application:
    name: msvc-estados
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-cloud.cf55fw7ygru8.us-east-1.rds.amazonaws.com:5432/dbproyecto
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: create  # O el que mejor se ajuste a tu estrategia de gestión de esquema
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configuración de Eureka
eureka:
  instance:
    hostname: 52.44.23.198
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/