# aqui haremos las peticiones
server:
  port: 8080

my_ip:
  value: localhost


spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: usuarios
            uri: lb://msvc-usuarios
            predicates:
              - Path=/api/signup/**
              - Path=/api/signin/**
              - Path=/usuarios/**
          - id: respuesta
            uri: lb://msvc-respuestas
            predicates:
              - Path=/api/respuestas/**
          - id: hilos
            uri: lb://msvc-hilos
            predicates:
              - Path=/api/hilos/**
          - id: estados
            uri: lb://msvc-estados
            predicates:
              - Path=/api/estados/**

# Configuración de Eureka
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/