server:
  port: 9094

# Configuración de Eureka

spring:
  application:
    name: msvc-capadeseguridad
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/